spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native  # for file path and class path
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Saugatsaugat/microservices-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "file:///home//saugat//Desktop//JAVA//Collection//config" # from file path
#          search-locations: "classpath:/config"  #from class path
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
server:
  port: 8071
