spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///home//saugat//Desktop//JAVA//Collection//config" # from file path
#          search-locations: "classpath:/config"  #from class path


server:
  port: 8071
